# These are supported funding model platforms

custom:  ['https://github.com/javthon/sponsor/blob/main/wechat.png', 'https://github.com/javthon/sponsor/blob/main/alipay.png','https://paypal.me/xxf666']
